modLoader = "javafml"
loaderVersion = "[${min_neoforge_fml_version},)"
issueTrackerURL = "${mod_issue_url}"
license = "${mod_license}"

[[mods]]
modId = "${modid}"
displayName = "${mod_name}"
version = "${mc_version}+${mod_version}"
description = "${mod_description}"
authors = "${mod_author}"
logoFile = "mod_logo.png"
displayURL = "${mod_page_url}"
updateJSONURL = "${mod_neoforge_update_url}"

[[mixins]]
config = "${modid}.common.mixins.json"

# Not needed, but when Configured is installed Glazed Menu sets its screens up after it, so mods' buttons open Glazed
# Menu's screens rather than Configured's.
[[dependencies.${modid}]]
modId = "configured"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${modid}]]
modId = "neoforge"
type = "required"
versionRange = "[${project.supported_min_neoforge_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${modid}]]
modId = "minecraft"
type = "required"
versionRange = "[${project.supported_min_mc_version},${max_mc_version}]"
ordering = "NONE"
side = "CLIENT"
